### ISSUE TITLE
How to run demo

### ISSUE THREAD

**Issue by ozgursevgi** [Whiroo/KiddyAPI#1]
project simple class how run pls demo

**Comment by Whiroo** [comment]
Hi, here is 
[KiddySimpleClass.zip](https://github.com/Whiroo/KiddyAPI/files/3403404/KiddySimpleClass.zip)
a simple class for example, if you don’t understand something, write to me

**Comment by ozgursevgi** [comment]
How to use and how to compile as exe

**Comment by Whiroo** [comment]
Step 1:
![Step1](https://user-images.githubusercontent.com/32369775/61457930-167a7200-a972-11e9-8e77-3be3b0f07b85.png)
Step 2:
![Step2](https://user-images.githubusercontent.com/32369775/61457950-22663400-a972-11e9-86d8-9b12fa1021cc.png)
Step 3:
![Step3](https://user-images.githubusercontent.com/32369775/61457957-28f4ab80-a972-11e9-8b5d-880df0bca421.png)
Step 4:
![Step4](https://user-images.githubusercontent.com/32369775/61457965-2f832300-a972-11e9-9107-47be1b8731b8.png)
Step 5:
![Step5](https://user-images.githubusercontent.com/32369775/61457971-36119a80-a972-11e9-96bc-b67bf53f5bbe.png)
Step 6:
![Step6](https://user-images.githubusercontent.com/32369775/61457977-3ca01200-a972-11e9-8588-05843b5dd916.png)
Step 7:
![Step 7](https://user-images.githubusercontent.com/32369775/61457998-49246a80-a972-11e9-93ee-a38fb627ea97.png)
Step 8:
![Step7](https://user-images.githubusercontent.com/32369775/61458051-65c0a280-a972-11e9-919d-4a3dc60ea1a3.png)
Step 9: Create new Project and add usings and code
![Step8](https://user-images.githubusercontent.com/32369775/61458066-6f4a0a80-a972-11e9-9289-8d47d77234b1.png)

**Comment by ozgursevgi** [comment]
Thanks
